// Code generated by raindrop build, DO NOT EDIT.
import { Ai, Annotation, App, Bucket, KvCache, Logger, MRNObject, SmartMemory, SmartSql, Tracer,  } from '@liquidmetal-ai/raindrop-framework';

export interface Env {
  _raindrop: {
    app: App;
  };
  AI: Ai;
  annotation: Annotation<Omit<MRNObject, 'type' | 'applicationName' | 'versionId'>>;
  AUDIO_STORAGE: Bucket;
  ELEVENLABS_API_KEY: string;
  logger: Logger;
  mem: KvCache;
  STORY_CONTEXT: SmartMemory;
  STORY_DB: SmartSql;
  STORY_MODEL: string;
  tracer: Tracer;
  TTS_VOICE_ID: string;
  VULTR_API_KEY: string;
}
